apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler-db
  name: scheduler-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler-db
    spec:
      containers:
        - args:
            - -p
            - "5434"
          env:
            - name: POSTGRES_DB
              value: scheduler
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: scheduler-db
          ports:
            - containerPort: 5434
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: scheduler-db-claim0
      restartPolicy: Always
      volumes:
        - name: scheduler-db-claim0
          persistentVolumeClaim:
            claimName: scheduler-db-claim0
status: {}
