apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler-db
  name: scheduler-db
spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5434
  selector:
    io.kompose.service: scheduler-db
status:
  loadBalancer: {}
