apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: we-connect-ingress
  
spec:
    rules:
      - host: we-connect.com
        http:
          paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-backend
                port:
                  number: 8000
          - path: /profile
            pathType: Prefix
            backend:
              service:
                name: profile-backend
                port:
                  number: 8001
          - path: /scheduler
            pathType: Prefix
            backend:
              service:
                name: scheduler-backend
                port:
                  number: 3001
